#Lightweight Python image
FROM python:3.11-slim

# Set working directory inside the container
WORKDIR /app

#Copy dependency list and install
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

#copy the app code
COPY app/app.py .

#Copy the model file
COPY model/model.pkl .
COPY model/vectorizer.pkl .

#Expose the FastAPI port
EXPOSE 8000

#Run the FastAPI app
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port","8000"]